title:              "디지털 마케팅 튜토리얼"
tagline:            "따라하면서 시작하는 실전 디지털 마케팅"
email:              "dayoon.jeong9@gmail.com"
description:        "차근차근 따라하면 할 수 있어요! 디지털 마케팅 실무자를 위한 마케팅 정보 블로그입니다."
author:             "Carry J"
baseurl:            "/"
url:                "https://hard-carry.com"
locale:             "ko_KR"
thumbnail:          "/img/thumbnail.jpg"

# Social Profiles
twitter_username:   twitter_username
instagram_username: instagram_username
facebook_username:  facebook_username
linkedin_username:  linkedin_username

# Build settings
markdown:           kramdown
permalink:          /:title
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-paginate

# 블로그 disqus shortname
disqus:
  shortname: digitalmarketingtutorial
